apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
spec:
  volumes:
  - name: kafka-storage-volume
    persistentVolumeClaim:
      claimName: datadir-0-kafkaconnect-cp-kafka-0
  containers:
  - name: cleanup-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    volumeMounts:
      - mountPath: "/var/logs"
        name: kafka-storage-volume
